name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: macos-latest
    
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: '5.10'
    
    - name: Import Code-Signing Certificates
      uses: apple-actions/import-codesign-certs@v3
      with:
        p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
    
    - name: Build and Sign
      run: |
        echo "Building the project..."
        swift build -c release
        echo "Moving binary to current directory..."
        mv .build/release/mwm ./mwm
        
        echo "Checking binary details before signing..."
        file ./mwm
        otool -L ./mwm
        
        echo "Attempting to sign the binary..."
        /usr/bin/codesign --force -s "${{ secrets.DEVELOPER_ID_APPLICATION }}" -v ./mwm
        
        echo "Verifying code signature..."
        /usr/bin/codesign -dv --verbose=4 ./mwm
        
        echo "Checking Gatekeeper assessment..."
        spctl --assess -vv ./mwm
        
        echo "Displaying entitlements..."
        codesign -d --entitlements :- ./mwm
    
    - name: Check Notarization Status
      run: |
        echo "Checking notarization status..."
        xcrun notarytool info ./mwm --apple-id "${{ secrets.APPLE_ID }}" --password "${{ secrets.APPLE_ID_PASSWORD }}" --team-id "${{ secrets.TEAM_ID }}"
    
    - name: Generate SHA256
      run: shasum -a 256 mwm > mwm.sha256
    
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          mwm
          mwm.sha256
        generate_release_notes: true