name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: macos-latest
    
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: '5.10'
    
    - name: Import Code-Signing Certificates
      uses: apple-actions/import-codesign-certs@v3
      with:
        p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
    
    - name: Build and Sign
      run: |
        swift build -c release
        mv .build/release/Mac-Windows-Manager ./mwm
        /usr/bin/codesign --force -s "${{ secrets.DEVELOPER_ID_APPLICATION }}" ./mwm
    
    - name: Generate SHA256
      run: shasum -a 256 mwm > mwm.sha256
    
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          mwm
          mwm.sha256
        generate_release_notes: true