name: Build and Release

on:
  push:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: macos-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: '5.10'
    
    - name: Build
      run: |
        swift build -c release
        mv .build/release/Mac-Windows-Manager ./Mac-Windows-Manager
    
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create v${{ github.run_number }} ./Mac-Windows-Manager \
          --title "Release ${{ github.run_number }}" \
          --notes "Automated release for commit ${{ github.sha }}"