name: Build and Release

on:
  push:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: macos-latest
    
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: '5.10'
    
    - name: Build
      run: |
        swift build -c release
        mv .build/release/Mac-Windows-Manager ./Mac-Windows-Manager
    
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: Mac-Windows-Manager
        generate_release_notes: true